### ISSUE TITLE
Can not start three containers with published ports, if using two NAT networks

### ISSUE THREAD

**Issue by leojth** [microsoft/Windows-Containers#486] opened 2024-04-16 11:32 UTC
**Describe the bug**
On Windows Server 2022 I can not start three (or more) containers with published ports, if using two (or more) NAT networks.
It works perfectly in Windows Server 2019.

When starting the third container, the command hangs indefinitely until the first container is stopped. The Windows Service "Host Network Service" will also take allot of CPU during that time.

**To Reproduce**
1. Have a Windows Server 2022 with Docker Engine installed. Open PowerShell as Administrator.

2. Create two NAT networks
```
docker network create --driver=nat --subnet=192.168.101.0/24 net1
docker network create --driver=nat --subnet=192.168.102.0/24 net2
```

3. Start three containers with published ports
```
docker run -d --network=net1 --publish 6001:6001 --name container1 mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd /s /c ping -t 127.0.0.1
docker run -d --network=net2 --publish 6002:6002 --name container2 mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd /s /c ping -t 127.0.0.1
docker run -d --network=net2 --publish 6003:6003 --name container3 mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd /s /c ping -t 127.0.0.1
```

The third command will now hang. It can not be aborted with CTRL+C. When running `docker ps -a` the status of the container is "Created". If trying to kill or remove the container, that command also hangs.

**Expected behavior**
The third container should be started as the other two and the command should return.

**Configuration:**
 - Edition: Windows Server 2022
 - Base Image being used: mcr.microsoft.com/windows/nanoserver:ltsc2022
 - Container engine: Docker
 - Container Engine version: 26.0.1 (have also tried 25, 24 and 23)
 - Isolation mode: process

**Additional context**
Running the third container in a separate third NAT network gives the same result.

Full [Docker logs here](https://github.com/microsoft/Windows-Containers/files/14996011/dockerd.log), but when the command hangs, the last log entry is:
```
[POST]=>[/endpoints/] Request : {"VirtualNetwork":"19E54EF9-D686-4658-AE9C-EC65DC6DAD0E","Policies":[{"Type":"NAT","Protocol":"tcp","InternalPort":6003,"ExternalPort":6003,"ExternalPortReserved":true}],"EnableInternalDNS":true}
```
Image below showing high CPU load on "Host Network Service" when trying to run third container.
![taskmanager](https://github.com/microsoft/Windows-Containers/assets/5588530/9427c1bc-9896-4d26-bbe0-a10a3de1c592)

Image below showing result of `docker ps -a` when trying to run third container.
![bild](https://github.com/microsoft/Windows-Containers/assets/5588530/33abe997-ecaa-4218-be0f-f986a8bd814b)

**Comment by fady-azmy-msft** [comment] 2024-04-17 17:10
Thanks for raising this issue @leojth, I've created an internal ticket for this bug (# 50179353). We'll look at this issue soon.

**Comment by Ramunasoft** [comment] 2024-05-23 23:29
@fady-azmy-msft @adrianm-msft the root cause of this bug is the same as [140: Can't start any two docker-compose environments](https://github.com/microsoft/Windows-Containers/issues/140) and [484: Container start hangs if it was created from another container](https://github.com/microsoft/Windows-Containers/issues/484)

I recommend this issue be closed and 140 be used to track as it is currently assigned.

**Comment by adrianm-msft** [comment] 2024-05-28 16:55
Thanks @Ramunasoft, I will close this issue and we will continue tracking the progress under issue #140.

**Closed as completed by adrianm-msft** 2024-05-28 16:55 UTC
Labels: bug, Networking
