### ISSUE TITLE
Host Networking Service [HNS] Crashes Causing Traffic Interruptions 

### ISSUE THREAD

**Issue by MikeZappa87** [microsoft/Windows-Containers#278] opened 2022-10-04 14:12 UTC
**Describe the bug**
The host networking service exits unexpectedly causing network traffic to drop. The current mitigation is to restart kube-proxy on the impacted nodes [note this can take time to fully restore the policy and make the node useable]. 

**To Reproduce**
None currently exist

**Configuration:**
 - Edition: Windows Server 2019/2022

**Additional context**

Possible Related Issues:
- https://github.com/kubernetes/kubernetes/issues/110674
- https://github.com/kubernetes/kubernetes/issues/110849
- https://github.com/Azure/AKS/issues/2899

**Comment by zhiweiv** [comment] 2022-10-05 09:31
@MikeZappa87 
~~Do you know how to check if HNS service crashed? https://github.com/kubernetes/kubernetes/issues/110849 still occur often in our environment, I want to check if it is related.~~

I found there is a remediation for AKS now, https://github.com/Azure/AgentBaker/pull/2085, I will check hnsremediator log when https://github.com/kubernetes/kubernetes/issues/110849 happen again.

**Comment by zhiweiv** [comment] 2022-10-07 05:06
I found there is a remediation for AKS now, https://github.com/Azure/AgentBaker/pull/2085.

**Comment by AbelHu** [comment] 2022-11-21 02:01
> Add any other context about the problem here.

@zhiweiv I think that this HNS crash issue has been fixed in AKS Windows images with 2022.11B on AKS. https://github.com/Azure/AgentBaker/pull/2427/files

**Comment by zhiweiv** [comment] 2022-11-21 03:06
I have updated AKS to AKSWindows-2019-containerd-17763.3650.221110 last Friday, let's see if it works without problem.

**Comment by kishorerv25** [comment] 2022-12-03 15:19
We have observed network connection exception's  for  service deployed in windows node.
This appeared after updating node image to AKSWindows-2019-containerd-17763.3650.221110 

System.Net.Sockets.SocketException (11001): No such host is known
 System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time

Issue is fixed with restart of pod and it got re-scheduled to another node. And node also deleted during scale-down operation.
This may appear again , Let me know logs or any other data which can be collected to validate if this issue comes again.

**Comment by SteveCurran** [comment] 2023-02-01 21:57
@kishorerv25 Apparently, you must get a special key to put in the registry to enable the fix for Windows2019?
https://support.microsoft.com/en-us/topic/october-25-2022-kb5018485-os-build-20348-1194-preview-becf7d1a-9482-4d56-955d-097e35b992a4

**Closed as completed** 2023-03-28 19:55 UTC
Labels: bug

**Comment by tzifudzi** [comment] 2023-06-02 21:32
I understand this issue is closed, but we are experiencing a similar issue on WS2022 even after the fix in [this Windows OS build](https://support.microsoft.com/en-us/topic/october-25-2022-kb5018485-os-build-20348-1194-preview-becf7d1a-9482-4d56-955d-097e35b992a4). One of they key problems with this issue is that it is hard to reproduce in order to effectively debug it. 

@MikeZappa87
1. Can you please help in advising how this issue can be reproduced if you managed to gain any further insights on that?
2. Is there any way to determine if the traffic interruptions we are experiencing are related to this issue so we can know if the cause is the same e.g. checking for specific log events?
