### ISSUE TITLE
Windows server 2004 has IIS application pool connection limit of 10

### ISSUE THREAD

**Issue by azkamil** [microsoft/Windows-Containers#73] opened 2020-11-11 16:30 UTC
Hi,

In our docker build we changed our base windows image from 1809 to **mcr.microsoft.com/windows:2004**
After this our application(on IIS) runs into timeout under a minimal load and no connection can be established.
Analyzing w3wp dump gave us a hint that the cause maybe the max connection count of 10 per IIS application pool. As seen in the screenshot the number stopped increasing at 10. In 1809 we had over 70 connections.
This is somehow very similar to the limit of 10 for Desktop Windows version.
This problem did not occurred while testing with **mcr.microsoft.com/windows/servercore:2004** . The connection count went over 20. We cannot use servercore version due missing functionality.

![10con](https://user-images.githubusercontent.com/2872951/98837225-fd3ce500-2442-11eb-94da-145f0bc0ef88.PNG)

FYI As a host windows version we use Azure OS image sku: datacenter-core-2004-with-containers-smalldisk

Thanks

**Comment by Hvid** [comment] 2020-11-19 14:56
It would be nice with a full image based on windows server instead of client. Web Management Service(WMSvc) doesn't work in the client version either.

**Comment by Josefczak** [comment] 2020-11-27 14:13
Could be solved by not using Windows Server 2004 but Windows Server 1809, when it would be extended as the Nano Server SAC1809 was.
https://github.com/microsoft/Windows-Containers/issues/52

**Comment by vrapolinario** [comment] 2020-12-04 23:51
Can you please confirm the previous image you were using and was able to get over 10 connections? Is it windows:1809 or servercore:1809?

**Comment by Josefczak** [comment] 2020-12-05 14:06
Hi everyone,

we are currently using windows:1809 in production (for many thousand customers in US, Europe and Japan) and have no problems (more than 10 connections) when using the

Publisher: MicrosoftWindowsServer
Offer: WindowsServer
SKU: 2019-Datacenter-with-Containers
Version: latest

as a host. We didn’t try it on a Windows Server Core host.

Best regards,
Thomas Josefczak

**Comment by vrapolinario** [comment] 2020-12-08 18:43
We did an internal investigation and found out what happened here:
The 10 connections limit is by design on the windows image, however a bug we preventing us from enforcing this on previous images. This bug was fixed and the behavior is now back in place.

With the above said, I wanted to understand why the windows image is being used for web/IIS purposes? This image is considerably larger than the server core one, which would be a better fit for IIS scenarios.

**Comment by quangkieu** [comment] 2020-12-08 18:55
So you are recommend start from the iis or aspnet image, not from the window or .NET images?

**Comment by vrapolinario** [comment] 2020-12-08 18:58
The IIS can be used for generic web content/apps, but for .Net there specific images as well (such as Asp.Net), that are actually based off of IIS. These are all in turn based on the server core image and won't have the same limitation.

**Comment by Josefczak** [comment] 2020-12-09 07:28
How could you decide such a limit? 
The image is described as a windows server image. Nobody knows about such a limit. After 3 weeks Azure Rapid Response Support - no one even believed us, that such a limit could exist. They denied it multiple times. And by the way, you as a Program Manager for containers didn't know either.
![image](https://user-images.githubusercontent.com/11995612/101598196-14e29b80-39f8-11eb-849b-767caa0eb3d6.png)

https://hub.docker.com/_/microsoft-windows

And to answer your question. We need the full windows image, because several rendering libraries we need for our document management software do not work with the windows server core image.

**Comment by Hvid** [comment] 2020-12-09 08:06
We're using the 'windows' image, because of missing components from the server core image as described in: https://github.com/microsoft/Windows-Containers/issues/58

We're falling back to this image, because of missing cdosys.dll, support for older MS access databases and so on. Another limitation to this image, is that the Web Management Service(wmsvc) will not listen on 8172 in client OS.

This is why we need a Windows Server image, and not a Windows 10 image.

**Comment by vrapolinario** [comment] 2020-12-09 21:38
@Josefczak Please note the "Windows Server" containers is the feature name to run containers on Windows Server. The next phrase on that description clearly state the Windows base OS image.

I understand the request here now, thanks for pointing it out. We're investigating the option to add some of the components mentioned on #58 but if there's anything in addition, please add to that issue.
For this one, the limitation mentioned is by design so I'll be closing it. Please note I'm just switching the context to the issue at hand, which is outside the limitation on the windows image.

**Closed as completed by vrapolinario** 2020-12-09 21:38 UTC
