### ISSUE TITLE
Can't connect to container hosted on Windows Server

### ISSUE THREAD

**Issue by altwohill** [microsoft/Windows-Containers#248] opened 2022-07-19 03:54 UTC
**Not sure if bug or question ;)**
Since a recent reboot, our devops build server is no longer able to connect to container images it starts. 
The container starts, and states that it is forwarding the port. But I can't connect to it, and netsh doesn't show the port as listening. 

**To Reproduce**
Dockerfile:
```
# SQL Server 2019 Windows container dockerfile
## Warning: Restarting windows container causes the machine key to change and hence if you have any encryption configured then restarting SQL On Windows containers
## breaks the encryption key chain in SQL Server. 

# Download the SQL Developer from the following location  https://go.microsoft.com/fwlink/?linkid=866662 and extract the .box and .exe files using the option: "Download Media"

FROM mcr.microsoft.com/windows/servercore:ltsc2022

ENV sa_password="_" \
    attach_dbs="[]" \
    ACCEPT_EULA="_" \
    sa_password_path="C:\ProgramData\Docker\secrets\sa-password" \
    install_source="http://examplesource"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# download install files
RUN invoke-webrequest -Uri $env:install_source/start.ps1 -outfile /start.ps1;  \
    invoke-webrequest -Uri $env:install_source/SQLServer2019-DEV-x64-ENU.box -outfile /SQLServer2019-DEV-x64-ENU.box; \
    invoke-webrequest -Uri $env:install_source/SQLServer2019-DEV-x64-ENU.exe -outfile /SQLServer2019-DEV-x64-ENU.exe

WORKDIR /
RUN dir
RUN Start-Process -Wait -FilePath .\SQLServer2019-DEV-x64-ENU.exe -ArgumentList /qs, /x:setup ; \
        .\setup\setup.exe /q /ACTION=Install /INSTANCENAME=MSSQLSERVER /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\NETWORK SERVICE' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS ; \
        Remove-Item -Recurse -Force SQLServer2019-DEV-x64-ENU.exe, SQLServer2019-DEV-x64-ENU.box, setup

RUN stop-service MSSQLSERVER ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\' -name LoginMode -value 2 ;

HEALTHCHECK CMD [ "sqlcmd", "-Q", "select 1" ]

CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
```
docker-compose.yml

```
services:
  db:
    environment:
      SA_PASSWORD: "my-secure-password!"
      ACCEPT_EULA: "Y"
    build:
      context: .
    expose:
      - 1433
    ports:
      - 14337:1433
```

**Expected behavior**
* ✅ `docker ps` to show the container with ports `0.0.0.0:14337->1433/TCP` 
* ❌ `netstat -ano` to show something listening on 14337
* ❌ `Test-NetConnection -Port 14337 -ComputerName 127.0.0.1` to succeed

**Configuration:**
 - Edition: Windows Server 2022 (21H2 Build 20348.768)
- Base Image being used: Windows Server Core
 - Container engine: docker
 - Container Engine version: Docker version 20.10.9, build 591094d

**Additional context**

**Comment by fady-azmy-msft** [comment] 2022-07-20 16:21
Can you clarify what was rebooted in this scenario @altwohill ?

**Comment by altwohill** [comment] 2022-07-20 19:21
The host server
________________________________

**Comment by fady-azmy-msft** [comment] 2022-07-20 22:50
Got it. I've opened a MSFT internal issue (40546521) to track this issue and reached out internally.

**Comment by fady-azmy-msft** [comment] 2022-11-02 15:59
No update to share except that we are looking into this.

**Comment by fady-azmy-msft** [comment] 2023-07-04 00:06
We haven't been able to repro the issue; is this still happening and if so could you repro this issue with a WS2022 container? @altwohill

**Comment by MikeZappa87** [comment] 2023-08-22 16:51
@altwohill we are unable to reproduce this on our side. Are you able to see if this still happens on 2022? I am going to close this for now. Please feel free to reopen this.

**Comment by kestratt** [comment] 2023-09-06 17:39
Closing while we wait for a reply

**Closed as completed** 2023-09-06 17:38 UTC
Labels: question
