### ISSUE TITLE
Memory leak with container restarts

### ISSUE THREAD

**Issue by akrus** [microsoft/Windows-Containers#70] opened 2020-10-21 07:52 UTC
Hello!

We've been testing Windows Containers for a while and found that at least SAC versions 1909 and 2004 have memory leaks when containers are being started.

How to reproduce:
(containerd)
```
ctr.exe run --rm mcr.microsoft.com/windows/nanoserver:2004 argon-test cmd /c "echo Hello World!"
```
(docker)
```
docker run --rm mcr.microsoft.com/windows/nanoserver:2004 cmd /c "echo Hello World!"                                                                                                                      
```

Run above in a loop and see how memory usage slowly grows.

poolmon.exe shows the following:
```
UlHT Paged      2418 (   0)         0 (   0)     2418   633864192 (          0)      262144
```
with every container start the counter (2418) increases growing indefinitely, which requires us to reboot the nodes.

Note: Hyper-V isolation mode works properly, but results in higher memory usage, so not really suitable when many small containers are in use.

**Comment by jsturtevant** [comment] 2020-10-21 16:06
Are you seeing this behavior in WS 2019?  Does removing the container after it stops do anything?

**Comment by akrus** [comment] 2020-10-22 11:45
We've tested WS 2019 LTSC and it's working fine there.

**Comment by immuzz** [comment] 2020-12-09 21:43
Closing this issue as we were not able to reproduce this issue or heard from anyone else facing this issue.

**Closed as completed by immuzz** 2020-12-09 21:43 UTC
Labels: perf
