### ISSUE TITLE
Docker installation via Windows Admin Center extension failed.

### ISSUE THREAD

**Issue by gabrielluizbh** [microsoft/Windows-Containers#429] opened 2023-10-07 15:09 UTC
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
When trying to install the Docker extension on Windows Admin Center, it fails.

![windowscontainers](https://github.com/microsoft/Windows-Containers/assets/31531703/bd720357-695a-4920-bf37-342c2774d149)

**To Reproduce** 

I attempted to install Docker through the Windows Admin Center.

**Expected behavior**

Docker installation through Windows Admin Center goes without any problems.

**Configuration:**

 - Edition: Windows Server 2022 Core
- Windows Admin Center: Version 2306
- Extension Container: Version 2.29.0

**Additional context**

After installing Docker using the command line in Powershell, the extension opened normally.
But it's worth reviewing the features to check if any other errors occur. I did not perform this test.
![windowscontainerse](https://github.com/microsoft/Windows-Containers/assets/31531703/584c8667-10a1-4b9c-97f2-4f07cf9b7a0f)

**Comment by fady-azmy-msft** [comment] 2023-10-12 18:12
Looking into this. FYI @lucillex and @iankingori 

Could you help me understand why you chose installing docker with WAC first instead of PowerShell? Very interested to hear your scenario and how frequent you need to do this. Thank you!

**Comment by gabrielluizbh** [comment] 2023-10-12 19:55
> Olhando para isso. FYI e
> 
> Você poderia me ajudar a entender por que você escolheu instalar o docker com WAC primeiro em vez do PowerShell? Muito interessado em ouvir o seu cenário e quão frequentemente você precisa fazer isso. Obrigado!

Just for practicality, anyone who clicks will be ready to deploy a Docker environment on Windows.

> Looking into this. FYI @lucillex and @iankingori
> 
> Could you help me understand why you chose installing docker with WAC first instead of PowerShell? Very interested to hear your scenario and how frequent you need to do this. Thank you!

Just for practicality, anyone who clicks will be ready to deploy a Docker environment on Windows.

**Comment by ntrappe-msft** [comment] 2023-11-23 00:56
🔖 ADO 47929261

**Comment by stoyanov-x** [comment] 2023-12-26 18:25
> Looking into this. FYI @lucillex and @iankingori
> 
> Could you help me understand why you chose installing docker with WAC first instead of PowerShell? Very interested to hear your scenario and how frequent you need to do this. Thank you!

It's worth noting that [Microsoft Learn](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-admin-center) states:

> You can use Windows Admin Center to properly set up a Windows Server machine as a container host.

Yet, when one uses WAC -> Containers, it fails with the above error. The error appears to be [caused by this deprecation from 2022 (extended until April 2023)](https://techcommunity.microsoft.com/t5/containers/important-update-deprecation-of-docker-virtual-machine-images/ba-p/3646272).

**Comment by gabrielluizbh** [comment] 2024-01-26 15:37
I would like to know if this error will be corrected?

**Comment by lucillex** [comment] 2024-01-29 23:16
Hi @gabrielluizbh, thanks for the ping. We're investigating this on our side.

**Comment by wimmatthyssen** [comment] 2024-01-31 13:58
Also having the same issue at the moment

When trying to install Docker via the containers extension via WAC on a Windows Server 2022, I receive the error "Couldn't install Docker" No match was found for the specified search criteria and package name 'docker'.

Any updates on this issue, or any way we can solve this installation error?

**Comment by gabrielluizbh** [comment] 2024-01-31 19:03
> Também tendo o mesmo problema no momento
> 
> Ao tentar instalar o Docker por meio da extensão de contêineres via WAC em um Windows Server 2022, recebo o erro "Não foi possível instalar o Docker" Nenhuma correspondência foi encontrada para os critérios de pesquisa especificados e o nome do pacote 'docker'.
> 
> Alguma atualização sobre este problema, ou qualquer maneira que podemos resolver este erro de instalação?

I'm glad it's not just me who has this problem.

**Comment by gabrielluizbh** [comment] 2024-01-31 19:13
> Também tendo o mesmo problema no momento
> 
> Ao tentar instalar o Docker por meio da extensão de contêineres via WAC em um Windows Server 2022, recebo o erro "Não foi possível instalar o Docker" Nenhuma correspondência foi encontrada para os critérios de pesquisa especificados e o nome do pacote 'docker'.
> 
> Alguma atualização sobre este problema, ou qualquer maneira que podemos resolver este erro de instalação?



> Also having the same issue at the moment
> 
> When trying to install Docker via the containers extension via WAC on a Windows Server 2022, I receive the error "Couldn't install Docker" No match was found for the specified search criteria and package name 'docker'.
> 
> Any updates on this issue, or any way we can solve this installation error?

Until Microsoft fixes the Windows Admin Center extension, use the link below to use Docker on Windows Server.

https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment

After manually installing Docker, you can use the Windows Admin Center extension to create images, but I do not recommend it until Microsoft engineers validate the entire Windows Admin Center Containers extension.

One detail is that the extension is not in preview, which should be checked and corrected more quickly by the product team.

**Comment by wimmatthyssen** [comment] 2024-02-01 15:56
That's exactly what I also did

**Comment by gabrielluizbh** [comment] 2024-04-18 21:55
No solution to the problem to date?

**Comment by gabrielluizbh** [comment] 2024-06-07 20:25
No solution to the problem to date?

**Comment by ntrappe-msft** [comment] 2024-06-12 18:30
We'd recommend _not_ using WAC to install Docker or containers. We're still discussing next steps for these features with the WAC team. In the meantime, you can install Docker using [Docker Desktop](https://www.docker.com/products/docker-desktop/) or [Docker CE](https://github.com/microsoft/Windows-Containers/tree/Main/helpful_tools/Install-DockerCE).

**Comment by ntrappe-msft** [comment] 2024-06-12 18:31
@gabrielluizbh I'm going to close this Issue for now but we'll notify you if anything changes.

**Closed as completed by ntrappe-msft** 2024-06-12 18:31 UTC
Labels: bug
