### ISSUE TITLE
Can't run mcr.microsoft.com/windows/nanoserver:1903 after update to latest Docker version

### ISSUE THREAD

**Issue by Antonytm** [microsoft/Windows-Containers#356] opened 2023-05-06 13:17 UTC
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
`docker run` fails after updating to latest Docker Desktop version

**To Reproduce** 
1. Open Terminal 
2. Run `docker run -it mcr.microsoft.com/windows/nanoserver:1903 cmd.exe`

**Expected behavior**
Command line to newly created container should be opened

**Configuration:**
 - Edition: Windows 10 Pro 22H2
- Base Image being used: nanoserver:1903
 - Container engine: Docker
 - Container Engine version Docker version 23.0.5, build bc4487a

**Additional context**
![image](https://user-images.githubusercontent.com/647813/236626548-c5cb9a9c-de00-418c-9c2a-33dcb88ca87b.png)

Event logs:
```
Handler for POST /containers/e0f88b2f6530a8e25b7015f9a57789dc50ecb577d36296ab1096a37415dec094/start returned error: container e0f88b2f6530a8e25b7015f9a57789dc50ecb577d36296ab1096a37415dec094 encountered an error during hcs::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)
```

```
e0f88b2f6530a8e25b7015f9a57789dc50ecb577d36296ab1096a37415dec094 cleanup: failed to delete container from containerd: no such container
```

```
failed to cleanup after a failed Start [error=container e0f88b2f6530a8e25b7015f9a57789dc50ecb577d36296ab1096a37415dec094 encountered an error during hcs::System::waitBackground: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106) module=libcontainerd namespace=moby]
```

```
failed to start container [module=libcontainerd error=container e0f88b2f6530a8e25b7015f9a57789dc50ecb577d36296ab1096a37415dec094 encountered an error during hcs::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106) namespace=moby]
```

**Comment by akarshm** [comment] 2023-05-09 23:24
@Antonytm: I see that you're running a 1903 container image (build 18362) on the 22H2 host (build 19045). Can you confirm whether this is process isolation or hyper-v isolation (docker run -it --isolation=hyperv mcr.microsoft.com/windows/nanoserver:1903 cmd)?

Note that Windows 10 version 1903 has reached [end of life](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1903-end-of-servicing).

**Comment by iankingori** [comment] 2023-05-12 12:41
Docker made a huge Docker Engine Upgrade between versions 4.18 to 4.19 from Engine v20.10.24 to Engine v23.0.5: https://docs.docker.com/desktop/release-notes/.

This error seems to be some sort of reverse regression of this https://github.com/docker/for-win/issues/4100 which was specific to Server 1903 images as well. In this case, specifying storage size caused the container startup to fail with: `The virtual machine or container exited unexpectedly. (0xc0370106)` 


### Mitigation
Explicitly specifying the storage size now appears to mitigate the problem: 
1. Run `docker.exe run --storage-opt "size=1GB" -it mcr.microsoft.com/windows/nanoserver:1903 cmd.exe`

Note: size must be `20GB or less`

**Comment by iankingori** [comment] 2023-05-12 16:06
The bug is brought about by 2 changes: 

1. In HCS Shim, a workaround was added to fix a bug on Server 1903 by expanding the volume soon after creating the Sandbox vhdx. This allowed us to specify storage options.  Details here: https://github.com/microsoft/hcsshim/pull/718/commits/d2042e6c90c526638eb5ef665eeed7a7199ed4d9

2. In Moby, the default sandbox size was increased to 127GB in this change: https://github.com/moby/moby/commit/56d378a88f27b42336d990764b3da9116584f296#diff-2dd8c745f6617be8aa5c94f0eb8884b5661d756997261985ef1dfba729e2568a

As a result of the above, for 1903 we are now trying to Create and Expand the Sandbox to 127GB  but there's a hard limit of 20GB on the OS (1903)due to a bug.

**Comment by fady-azmy-msft** [comment] 2023-05-12 19:32
Since this only affects EOL images, we are closing this issue.

**Closed as completed by fady-azmy-msft** 2023-05-12 19:33 UTC
Labels: bug
