### ISSUE TITLE
Container images for Windows 10 21H2 LTSC

### ISSUE THREAD

**Issue by rgl** [microsoft/Windows-Containers#192] opened 2021-12-27 06:25 UTC
When will we have base container images for Windows 10 21H2 LTSC (e.g. 10.0.19044.1415) that allow us to run containers in process isolation mode?

**Comment by L1ghtman2k** [comment] 2021-12-28 06:05
There are a few issues open on a similar topic, but FYI, i was able to run ltsc2022 images on windows 11 21H2 with process isolation

**Comment by TBBle** [comment] 2022-01-05 13:28
Yeah, basically a duplicate of #117, which was answered with ["no, all container images are from Windows Server"](https://github.com/microsoft/Windows-Containers/issues/117#issuecomment-886266148) and later ["still no, but you can run Server 2022 containers in process isolation on Windows 11 so this won't happen again in future"](https://github.com/microsoft/Windows-Containers/issues/117#issuecomment-912645956). There's _a lot_ more detail and discussion in the ticket, but that's the gist of the outcome as I understand it.

**Comment by cwilhit** [comment] 2022-02-22 18:50
Closing, since answer and convo is in #117

**Closed as completed by cwilhit** 2022-02-22 18:50 UTC
Labels: triage
