### ISSUE TITLE
VC++ Redistributables Fail to install on images with a Windows Server 2019 datacenter host

### ISSUE THREAD

**Issue by Jeb135** [microsoft/Windows-Containers#288] opened 2022-11-08 20:59 UTC
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
Opening this ticket as the result of a bug report and discussion in the dotnet-framework-docker repository (https://github.com/microsoft/dotnet-framework-docker/discussions/1017)

I am Unable to install Latest Visual C++ Redistributables (found here: https://aka.ms/vs/17/release/vc_redist.x64.exe) into windows containers. When the executable vc_redist.x64.exe runs inside the container either during a build or during runtime, nothing happens. This seems to be particularly an issue with Windows Server 2019 hosts, as when I tried this on a 2022 host VM, and upgraded the original host to 2022, the problem was resolved.

**To Reproduce** 
1. Build the following dockerfile `docker build -t redist_test:latest .`
```
# escape=`

# docker build -t redist_test:latest .
# docker run --rm -it --entrypoint powershell redist_test:latest

ARG BaseRepo=mcr.microsoft.com/dotnet/framework/aspnet
ARG BaseRepoTag=4.7.2

FROM $BaseRepo:$BaseRepoTag as base
SHELL ["Powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; $verbosePreference='Continue';"]

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; `
    Invoke-RestMethod -Uri https://aka.ms/vs/17/release/vc_redist.x64.exe -OutFile vc_redist_x64.exe; `
    Start-Process -filepath C:\vc_redist_x64.exe -ArgumentList "/install", "/passive", "/norestart", "'/log C:/redist_log.txt'" -Passthru | Wait-Process;
```
2. Run the image `docker run --rm -it --entrypoint powershell redist_test:latest`
3. Notice no log file from executable was created
4. Search for signs that the redistributable was installed in the container, such as `Get-Item -Path HKLM:\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64`, and you won't find anything.
5. Any assemblies that require the redistributables to run will fail to load.

**Expected behavior**
The executable runs and installs the redistributables as expected. The results of Step 4 in the reproduction steps would look the below indicating installation success:
```
Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes


Name                           Property
----                           --------
x64                            Version   : v14.32.31332.00
                               Installed : 1
                               Major     : 14
                               Minor     : 32
                               Bld       : 31332
                               Rbld      : 0
```
Additionally, assemblies that rely on the redistributables as a dependency successfully load.

**Configuration:**
 - Edition: Windows Server 2019 Datacenter
- Base Image being used: Windows Server core
 - Container engine: docker
 - Container Engine version: master-dockerproject-2022-03-26

**Additional context**
Original Bug Report in other repo: https://github.com/microsoft/dotnet-framework-docker/issues/1014
Original Discussion where the fix was found: https://github.com/microsoft/dotnet-framework-docker/discussions/1017

**Comment by fady-azmy-msft** [comment] 2022-11-23 17:52
Hey @Juarezhm, any thoughts on this?

**Comment by michbern-ms** [comment] 2023-01-14 01:04
I have access to a Windows Server 2022 host and ran the repro steps there, and confirmed that the problem does *not* reproduce on Server 2022.

@Jeb135 If you force the container to run in HyperV isolated mode using the "--isolation hyperv" switch, does the problem still occur?  I am wondering if it is related to the container mode.

Of course, Server 2022 has been on the market for over a year, so I would recommend that you move up to Server 2022 in any case.

**Comment by slonopotamus** [comment] 2023-01-14 09:40
> I would recommend that you move up to Server 2022 in any case

No problem, just send us licenses.

MS claims Server 2019 is supported until Jan 9, 2029.

**Comment by Jeb135** [comment] 2023-01-16 06:15
@michbern-ms I cannot confirm this as the Server 2019 machine has long been upgraded to resolve this issue, but I do remember attempting hyperv isolation with no success.

**Comment by michbern-ms** [comment] 2023-01-17 02:56
@Jeb135 Thank you for getting back to me.   I took the time this weekend to try this out - I set up a Server 2019 machine and ran your instructions exactly.

Unfortunately, I was not able to reproduce the problem.  

I used the following versions:

![image](https://user-images.githubusercontent.com/99994515/212799395-e83fbad2-0f34-4bf1-b6d5-4872ab4f337d.png)

And your Dockerfile and commands copy-pasted into the machine.

At the end, I see:

![image](https://user-images.githubusercontent.com/99994515/212799507-4ada695f-83a8-46c1-b477-b79d7e98784a.png)

I am sure that you tried all this and documented it carefully.  I am wondering if we had a transitory failure, or if some issue not immediately related to Containers caused this, but is now fixed.   In any case, there is nothing further I can do here.  As far as I can tell, Server 2019 customers should be good to go at this point.

Thanks,
Michael

**Closed as completed** 2023-01-17 17:14 UTC
Labels: bug

**Comment by Jeb135** [comment] 2023-01-17 17:19
@michbern-ms I booted up a snapshot from 2 years ago of the offending machine to try this out and also did not run into this problem. There must be another factor or configuration issue involved that I am missing that occurred between this snapshot and when I ran into the problem a few months ago. In any case, looks like this one has gone cold. Thanks for looking into it.

**Comment by michbern-ms** [comment] 2023-01-17 19:08
Thanks very much, @Jeb135 , for trying the old snapshot!
