### ISSUE TITLE
StackoverflowException when running Windows Container image with mounted volume

### ISSUE THREAD

**Issue by fabiang** [microsoft/Windows-Containers#308] opened 2023-01-04 14:35 UTC
I'm trying to run a Windows Server Core Docker Image on a Windows machine with drive D: mounted into the container and the containers is exited with the following error:

```
Process is terminated due to StackOverflowException.
```

It looks like that OS version 10.0.17763.3770 from 2022-12-13 has broken Powershell. The impact should be huge as I've noticed this first [for Jenkins Inbound Agent](https://issues.jenkins.io/browse/JENKINS-70157), then though this is an [upstream bug of eclipse-temurin](https://github.com/adoptium/adoptium-support/issues/642) and now my own package [fabiang/wix3](https://github.com/fabiang/docker-wix3) is broken. Therefore more and more downstream images become broken.

**To Reproduce**
```
docker run -it --rm -v "d:\:d:" --entrypoint=powershell mcr.microsoft.com/windows/servercore:ltsc2019
```

Running the same image without the volume mount, Powershell is started:

```
docker run -it --rm --entrypoint=powershell mcr.microsoft.com/windows/servercore:ltsc2019
```

**Configuration:**
 - Edition: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.3650)
 - Base Image being used: Windows Server Core LTSC2019
 - Container engine: docker
 - Container Engine version 20.10.22

**Comment by michbern-ms** [comment] 2023-01-17 18:52
@fabiang - sorry to hear you are having trouble.  

I matched your configuration as best I could -- I don't have access to docker 20.10.22, but I tried 20.10.9 and the latest Docker CE version.  I could not reproduce the problem on either of those.

Docker 20.10.9:

![image](https://user-images.githubusercontent.com/99994515/212985180-343286b4-a7af-4359-9429-2f8c47e695ee.png)

Docker CE:

![image](https://user-images.githubusercontent.com/99994515/212985215-31d0a7a2-ff3c-4e93-a7e5-e28b40827168.png)


Is there something unusual in the PowerShell configuration?  I'd like to try to route this issue accurately, but so far it is not happening for me.

**Comment by fabiang** [comment] 2023-01-18 12:37
@michbern-ms Thank you very much for looking into this.

I've pulled a newer image with ID `2564578bc438` and still get error, but I found out how to reproduce the error :)

My daemon.json is different:

```json
{
    "data-root": "D:\\docker"
}
```

If I remove `data-root` from the config and restart the daemon it is working again. If `D:\docker` exists and `data-root` is removed it's also working.

I had changed the `data-root` long time ago and it was working for years, so I still believe something is broken in Powershell, since it went broken even without changing the system and/or updating Docker.

**Comment by michbern-ms** [comment] 2023-01-21 20:02
@fabiang That helps - I can reproduce it now.  Next step is to make some sense of the debugger dump I captured.  It may take some time to diagnose, since I'll need to loop in the PowerShell team.

Just an observation: since we are using Process Isolated containers in this situation, you are taking a drive letter that exists in the host and mapping it into the process-isolated guest in precisely the same location.  I am wondering if that situation is causing a recursive loop in PowerShell somehow, as the guest's D: and the host's D: resolve to the same place.   

Is it possible to map D: to some specific, different location in the guest to see if that helps?

**Comment by fabiang** [comment] 2023-01-23 10:13
The following command with `"data-root": "d:\\docker" works:

```
docker run -it --rm -v "d:\:e:" --entrypoint=powershell mcr.microsoft.com/windows/servercore:ltsc2019 dir E:
```

**Comment by michbern-ms** [comment] 2023-01-26 19:20
@fabiang I was able to get a debug log and to link it to a specific security servicing fix that went out in the December release.  This is consistent with your finding about OS version 10.0.17763.3770.   I shared the data with the Windows Servicing team, who are investigating.  

Just for my education, if you are comfortable sharing: why are you mapping the Docker data root into the container?  The docker data root has layer data and configuration data _about_ the container -- I would not have expected that you would want that data visible _within_ the container.   I'm curious to learn more.

**Comment by fabiang** [comment] 2023-01-26 19:49
@michbern-ms: good to hear the great news and fingers crossed that this will be fixed soon. 

The thing is, I don't want to access the data-root within the container, D: ist just the biggest drive and thats why I put the data-root there (Jenkins and many images; Windows images are huge). The working path of Jenkins is also on D: and since I'm using the inbound agent Docker images I need to mount D:. I didn't use a volume here because it's far easier for me to go to D:\workspace.

**Comment by michbern-ms** [comment] 2023-02-08 00:51
Update: the fix has been coded and tested, and now we are doing the work to prepare to backport the fix to existing releases.  This has to be done carefully since the fix goes to 1B+ Windows machines, so it takes some time.

We confirmed that you can work around this bug by not mapping the Docker data-root into the Container itself.  

I recognize from your description that the workaround may not be feasible, but I wanted to make sure the workaround method was clear.

**Comment by slonopotamus** [comment] 2023-02-08 08:40
> mapping the Docker data-root into the Container itsel

I'd say doing so is simply insecure. Container gains ability to sneak into other containers FS or even inject malicious code into downloaded image files.

**Comment by fabiang** [comment] 2023-02-08 13:51
> I'd say doing so is simply insecure.

Absolutely. I thought it's only possible to mount a whole drive into a container., but when reffering to the docs I guess I was just wrong.

**Comment by michbern-ms** [comment] 2023-05-22 16:10
The fix for this issue went out in the March patch release for Server 2019 and Server 2022.  You should not be seeing the issue any more at this time.

**Closed as completed** 2023-05-23 17:00 UTC
Labels: bug
